[project]
name = "hiro-qq"
version = "0.1.9"
description = "An Python Implementation of NTQQ PC Protocol, orignates from lagrange-python"
readme = "README.md"
license = "LGPL-2.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name="linwenxuan05"},
    {name="wyapx"},
    {name="Harcic"}
]
dependencies = [
    "cryptography>=46.0.7",
    "qrcode>=7.4.2",
    "typing-extensions>=4.7.0",
]
keywords = ["QQ", "Tencent", "NTQQ", "Framework", "Bot", "asyncio"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
]
requires-python = ">=3.10"

[project.optional-dependencies]
faster = ["ftea>=0.1.8"]
loguru = [
    "loguru>=0.7.2",
]

[dependency-groups]
dev = [
    "loguru>=0.7.2",
    "pyrefly>=1.2.0",
    "ruff>=0.16.1",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "lagrange"
module-root = ""

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "UP", "C", "T", "Q"]
ignore = ["E402", "F403", "F405", "C901", "UP037"]

[tool.ruff.lint.per-file-ignores]
"main.py" = ["T201"]

[tool.pyrefly]
preset = "default"
python-version = "3.10"
project-includes = ["lagrange"]
