name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v5
      name: Setup uv

    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"

    - run: uv sync --locked --all-groups --all-extras
      shell: bash
