name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Check Version
        env:
          TAG_VERSION: ${{ github.event.release.tag_name }}
        run: |
          test "$(uv version --frozen --short)" = "${TAG_VERSION#v}"

      - name: Build package
        run: uv build --clear

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
